Repository lightspeeddevelopment/lsx-blocks, pull requests merged in 2020-07, with the labels that each got.

#64 Fixing where the page title output
  classes/lib/class-page-title.php
Labels: bug, enhancement

#58 Allowing the Post Carousel to use a 1 column layout
  changelog.md
  dist/assets/js/frontend.js
  dist/blocks.build.js
  dist/blocks.editor.build.css
  dist/blocks.style.build.css
  src/blocks/block-post-carousel/edit.js
  src/blocks/block-post-carousel/styles/editor.scss
  src/blocks/block-post-carousel/styles/style.scss
Labels: enhancement

#66 Making sure that the page title class is added only when the page title is on
  classes/lib/class-page-title.php
Labels: enhancement

#68 Removing unused core blocks.
  changelog.md
  classes/lib/class-hero-banner.php
  dist/assets/js/editor.js
  dist/init.php
Labels: enhancement

#69 Adding compatibility with WordPress 5.5.
  changelog.md
  dist/blocks.build.js
  src/blocks/block-banner/index.js
  src/blocks/block-button/index.js
  src/blocks/block-card/bin/index.js
  src/blocks/block-card/index.js
  src/blocks/block-cta/index.js
  src/blocks/block-spacer/index.js
Labels: performance
