Repository lightspeeddevelopment/lsx-blocks, pull requests merged in 2020-03, with the labels that each got.

#47 making sure the Disable Title metabox only appears on posts, when the…
  classes/class-admin.php
  classes/class-frontend.php
Labels: bug

#48 Fixed - using the development version of react #45
  changelog.txt
  classes/class-setup.php
  dist/blocks.style.build.css
  src/blocks.js
  src/blocks/block-post-carousel/index.js
Labels: bug

#49 * Add - Adding compatible classes for WordPress 5.4+.
  changelog.txt
  dist/assets/js/frontend.js
  dist/blocks.build.js
  dist/blocks.editor.build.css
  dist/blocks.style.build.css
  src/blocks/block-accordion/styles/editor.scss
  src/blocks/block-accordion/styles/style.scss
  src/blocks/block-author-profile/styles/editor.scss
  src/blocks/block-button/styles/editor.scss
  src/blocks/block-card/styles/editor.scss
  src/blocks/block-container/styles/style.scss
  src/blocks/block-cta/styles/editor.scss
  src/blocks/block-post-carousel/styles/editor.scss
  src/blocks/block-post-grid/index.php
  src/blocks/block-post-grid/styles/editor.scss
  src/blocks/block-post-grid/styles/style.scss
  src/blocks/block-spacer/styles/editor.scss
  src/blocks/block-team/index.php
  src/blocks/block-team/style.scss
  src/blocks/block-testimonials/index.php
  src/blocks/block-testimonials/style.scss
  src/common.scss
Labels: enhancement

#50 Add support for "post tags" to both the post grid and carousel blocks
  changelog.txt
  dist/blocks.build.js
  dist/blocks.editor.build.css
  dist/blocks.style.build.css
  src/blocks/block-post-carousel/edit.js
  src/blocks/block-post-carousel/index.php
  src/blocks/block-post-carousel/styles/editor.scss
  src/blocks/block-post-grid/edit.js
  src/blocks/block-post-grid/index.js
  src/blocks/block-post-grid/index.php
  src/blocks/block-post-grid/styles/editor.scss
  src/blocks/block-post-grid/styles/style.scss
Labels: bug, enhancement

#51 Add/25 - Improve background settings for the Container block
  dist/blocks.build.js
  dist/blocks.editor.build.css
  dist/blocks.style.build.css
  src/blocks/block-button/index.js
  src/blocks/block-container/components/inspector.js
  src/blocks/block-container/index.js
  src/blocks/block-container/styles/style.scss
Labels: enhancement
